/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercises07;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", new Object());
    }

    @Test public void test1() {
        assert(2==1+1);
    }
}
